### ISSUE TITLE
Package 'jenkins' has no installation candidate

### ISSUE THREAD

**Issue by KellMar** [ros-infrastructure/buildfarm_deployment#70] opened 2015-08-31 14:00 UTC
I just wanted to try the buildfarm and run the local deployment test.

The master isn't starting, i looked in the puppet log file and noticed, I'm missing the jenkins installation candidate:

2015-08-31 10:06:50 +0000 Puppet (err): Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install jenkins' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
Package jenkins is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'jenkins' has no installation candidate
2015-08-31 10:06:50 +0000 /Stage[main]/Jenkins::Package/Package[jenkins]/ensure (err): change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install jenkins' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
Package jenkins is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'jenkins' has no installation candidate
2015-08-31 10:06:50 +0000 /Stage[main]/Main/File[/etc/default/jenkins](notice): Dependency Package[jenkins] has failures: true

I don't know what to do.

**Comment by tfoote** [comment] 2015-08-31 18:15
It appears that jenkins has been pulled from upstream sources by the maintainer: https://bugs.launchpad.net/ubuntu/+source/jenkins/+bug/1294005

We will need to add the jenkins debian apt repo to the puppet config for this to work again: http://pkg.jenkins-ci.org/debian/ or probably we should use the LTS version at: http://pkg.jenkins-ci.org/debian-stable/

As a workaround you can manually add that repo to the apt sources on that machine and I expect puppet to be able to continue.

**Comment by KellMar** [comment] 2015-09-02 12:24
thanks, manually adding the repo worked.

MK.

**Comment by tfoote** [comment] 2016-01-06 04:35
Looking in a little deeper it looks like the apt repos are hard coded into the module, and as such I would expect them to be added automatically. Maybe this was fixed in a recent change. It's going to need some more testing.

**Comment by tfoote** [comment] 2016-01-06 05:54
I've been able to reproduce. Unfortunately it appears that the jenkins plugin does not force an apt-get update between adding the repository to the sources.list.d directory and trying to install jenkins. 

I was able to get past this by just running reconfigure a second time. There's an upstream issue here: https://github.com/jenkinsci/puppet-jenkins/issues/453 There's not much I can do without forking the module. I'll leave this open for visibility, but running it twice should be fine.

**Comment by gavanderhoorn** [comment] 2017-05-16 16:23
I've been deploying buildfarm masters for some days now and finally got round to addressing this (or: I got fed up with having to run things manually / twice all the time).

My current fix (work-around?) is to add `pkg.jenkins.io/debian-stable` in an `apt::source` first, making sure it also imports the key. After that I change `include jenkins` into:

```puppet
class { 'jenkins': 
  repo => false,
  require => Class['apt::update']
}
```
to make sure puppet runs an `apt-get update` before trying to install the `jenkins` package.

I saw no other way to make puppet / the `jenkins` module do `apt-get update`.

If this is an acceptable change, I can prepare a PR.

**Comment by tfoote** [comment] 2018-01-12 19:56
I think that approach is overkill as it will force an update every time it checks for the jenkins version. But if that makes it work, it's probably worth the extra time.

It looks like there's a new suggested syntax to make sure that install is called after update here: https://forge.puppet.com/puppetlabs/apt#limitations

**Comment by gavanderhoorn** [comment] 2018-01-13 08:12
@tfoote: I don't know if it's overkill.

As I wrote earlier: I'm not really into puppet, but had a problem to solve.

If there is a better way, I'm all for it.

**Closed** 2018-01-22 22:16 UTC
Labels: blocked on upstream. workaround available
