### ISSUE TITLE
master deployment: slaves can't connect due to "JNLP TCP port" set to "disabled"

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/buildfarm_deployment#177] opened 2018-01-11 09:07 UTC
As per subject really.

Not sure whether this is due to configuration by puppet not completing because of other issues, but none of my slaves/agents can connect initially.

Errors seen: "slaveAgentPort.disabled Go to security configuration screen and change it."

Indeed after a master reconfigure the *TCP port for JNLP agents* is set to *Disable* in the *Configure Global Security* panel of the master configuration.

**Comment by gavanderhoorn** [comment] 2018-01-11 09:07
Setting this to *Random*, saving and restarting Jenkins makes all slaves come up.

**Comment by inigomartinez** [comment] 2018-01-19 09:26
> Setting this to Random, saving and restarting Jenkins makes all slaves come up.

When I tried this, the slaves disappeared 😞.

**Comment by gavanderhoorn** [comment] 2018-01-19 09:32
I had to restart the slaves after rebooting Jenkins.

**Comment by gavanderhoorn** [comment] 2018-01-22 21:19
@inigomartinez: did restarting the slaves work for you?

**Comment by nuclearsandwich** [comment] 2018-01-22 21:48
There's a new resource that will be introduced by #183  for running Groovy scripts via puppet.

http://javadoc.jenkins.io/jenkins/model/Jenkins.html#setSlaveAgentPort-int- and http://javadoc.jenkins.io/jenkins/model/Jenkins.html#setAgentProtocols-java.util.Set- are the API methods of relevance.

In the interest of secure defaults, even as they deviate from build.ros.org I think it would be best to try and only enable the v4 agent protocol (which uses TLS for secure communication).

**Comment by inigomartinez** [comment] 2018-01-23 10:14
> @inigomartinez: did restarting the slaves work for you?

No, it didn't worked just restarting, but the issue is fixed now. I didn't realize the JNLP2 option was disabled, so after enabling it, the slaves connected seamlessly :smiley:.

**Comment by gavanderhoorn** [comment] 2018-01-23 10:16
Ah, ok.

Simply restarting without changing the setting was not going to solve it no :)

**Comment by gavanderhoorn** [comment] 2018-01-23 10:51
@nuclearsandwich: just brought up a master deployment and without changing anything only the `Java Web Start Agent Protocol/4 (TLS encryption)` option is enabled.

**Comment by gavanderhoorn** [comment] 2018-01-23 11:11
Hm. Now I understand @inigomartinez's https://github.com/ros-infrastructure/buildfarm_deployment/issues/177#issuecomment-359743558: Jenkins `2.89.3` appears to by default disable all slave protocols except version 4 with TLS.

The slaves/agents seem to only support JNLP2, and can't connect now.

**Comment by gavanderhoorn** [comment] 2018-01-23 11:23
Only agents `v3.3` and up seem to support `JNLP4`, but that jar doesn't seem to want to cooperate when I drop it in-place of the `v2.2` that is currently deployed.

(is there some swarm plugin doc I'm missing that details which protocols are supported? Cause it's really hard to find)

**Comment by gavanderhoorn** [comment] 2018-01-23 12:21
Unfortunately enabling `JNLP2` to get the agents to connect results in Jenkins (`2.89.3`) to display the following warning:

> This Jenkins instance uses deprecated protocols: JNLP2-connect. It may impact stability of the instance. If newer protocol versions are supported by all system components (agents, CLI and other clients), it is highly recommended to disable the deprecated protocols.

**Comment by nuclearsandwich** [comment] 2018-01-23 16:39
Until we have a chance to test an updated swarm plugin I think we'll have to enable JNLP2 as well and live with the warning.

**Comment by jonazpiazu** [comment] 2018-09-19 09:05
> Only agents `v3.3` and up seem to support `JNLP4`, but that jar doesn't seem to want to cooperate when I drop it in-place of the `v2.2` that is currently deployed.

I am not sure if it is still relevant, but I just tried to "drop in place" the latest available version for the agent, which is [v3.4](https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.14/swarm-client-3.14.jar) and it seems to be working nicely.

Using Jenkins version 2.89.2 and JNLP4.

**Comment by nuclearsandwich** [comment] 2019-04-18 11:05
One of the changes in #207 was a forked version of the jenkins module we're using to allow proper installation of more recent swarm client versions. The version is now specified in the buildfarm_deployment_config, here's [the relevant entries in the example config](https://github.com/ros-infrastructure/buildfarm_deployment_config/blob/5a58ca8cf2ba96d0a176cbeb26aa28fa637788dd/hiera/hieradata/common.yaml#L9-L10).

I believe that with the move to more recent swarm clients and Jenkins' current defaults that no changes are needed for a secure instance with functioning swarm agents, so I'll close this one. But if someone is still having issues I am happy to re-open and/or help them investigate.

**Closed by nuclearsandwich** 2019-04-18 11:05 UTC
Labels: buildfarm role: master
